language: python
env:
- NOX_SESSION=lint
- NOX_SESSION=tests
install:
- pip install codecov
# Temporary until nox is published
- pip install git+https://github.com/jonparrott/nox
script: nox --session $NOX_SESSION
after_success: codecov
